ARG POSTGRES_VERSION=13

FROM postgres:${POSTGRES_VERSION}-alpine3.17 AS pgvector-builder
ENV PGVECTOR_VERSION=${PGVECTOR_VERSION}

RUN apk add git
RUN apk add build-base
RUN apk add clang
RUN apk add llvm15-dev llvm15
WORKDIR /home
RUN git clone https://github.com/pgvector/pgvector.git
WORKDIR /home/pgvector
RUN make
RUN make install

FROM postgres:${POSTGRES_VERSION}-alpine3.17
COPY --from=pgvector-builder /usr/local/lib/postgresql/bitcode/vector.index.bc /usr/local/lib/postgresql/bitcode/vector.index.bc
COPY --from=pgvector-builder /usr/local/lib/postgresql/vector.so /usr/local/lib/postgresql/vector.so
COPY --from=pgvector-builder /usr/local/share/postgresql/extension /usr/local/share/postgresql/extension

CMD ["postgres"]
